### ISSUE TITLE
Newly created wallets are not being authenticated with ton_proof

### ISSUE THREAD

**Issue by mohsinrazabmd** [ton-connect/demo-dapp-with-react-ui#17]
![Screenshot 2024-08-02 171630](https://github.com/user-attachments/assets/55809933-2bf6-4baa-b670-88541f03644b)

I installed tonkeeper and created a new wallet on new phone that never used tonkeeper before, and it cannot be authenticated with ton_proof, creating new wallet with phone that already had tonkeeper few months few and it works, but not on new phones

**Comment by mzspcgg** [comment]
It also doesn't work for me.

```
// 1. First, try to obtain public key via get_public_key get-method on smart contract deployed at Address.
      // 2. If the smart contract is not deployed yet, or the get-method is missing, you need:
      //  2.1. Parse TonAddressItemReply.walletStateInit and get public key from stateInit. You can compare the walletStateInit.code
      //  with the code of standard wallets contracts and parse the data according to the found wallet version.
      let publicKey = tryParsePublicKey(stateInit) ?? await getWalletPublicKey(payload.address);
      if (!publicKey) {
        return false;
      }
```

Also in the code above looks like there is a wrong order. I think it should firstly check publicKey on blockchain using getWalletPublicKey and if there wasn't any transaction it should use tryParsePublicKey. However, tryParsePublicKey doesn't work if the wallet has just been created.

**Comment by Edgar-P-yan** [comment]
Having the same problem. After some digging found out that the new wallet's code only matches to `WalletContractV5R1` which seems like was made public only 3 weeks ago at commit https://github.com/ton-org/ton/commit/d4459d5491d57aa4fb1870ed578db644994225ef. This demo does not include `WalletContractV5R1` to it's `knownWallets` at https://github.com/ton-connect/demo-dapp-with-react-ui/blob/b669298fc1e9709044c8bbe606b5d9029c5659ad/src/server/wrappers/wallets-data.ts#L16 so i added it myself, and i also added the `WalletContractV5Beta` just in case although it's marked as deprecated. When i test, the wallet's code match, but there is no description on how to implement a `loadWalletV5Data` function to parse the slice, so i just copied one from v4, the result looks like this:
```ts
function loadWalletV5Data(cs: Slice) {
  const seqno = cs.loadUint(32);
  const walletId = cs.loadUint(32);
  const publicKey = cs.loadBuffer(32);
  const plugins = cs.loadMaybeRef();
  return { seqno, publicKey, walletId, plugins };
}
```
 This function does give me a `publicKey`, but it does not match to the `wantedPublicKey` given to me from the client so the `if` check fails at https://github.com/ton-connect/demo-dapp-with-react-ui/blob/b669298fc1e9709044c8bbe606b5d9029c5659ad/src/server/services/ton-proof-service.ts#L51
 
Summary: new wallets are based on new V5 version, but there is basically no documentation on how to connect it (or i didn't look for it well enough). Also this demo should include `WalletContractV5R1` to it's `knownWallets`. For now stuck with it and waiting for help from the ton-connect team :)

**Comment by mohsinrazabmd** [comment]
Hello @Edgar-P-yan and @mzspcgg I found the solution, you can actually authenticate new wallets using state init data, it was written in ton proof documentation
![image](https://github.com/user-attachments/assets/a2bfbe55-9179-4cc5-8c5d-2d500ca27199)
It worked for me and it doesn't need to call get methods from contracts, although I am not sure if it is as much secure as the previous one

**Comment by mohsinrazabmd** [comment]
Here is the source code before I close this issue:

Backend

```
//imports
import {
  Address,
  Cell,
  contractAddress,
  loadStateInit,
  Slice,
  Builder,
} from "@ton/ton";
import { Buffer } from "buffer";
   const stateInit = loadStateInit(
        Cell.fromBase64(payload.proof.state_init).beginParse()
      );

      if (!allowedDomains.includes(payload.proof.domain.value)) {
        console.log(
          "!allowedDomains.includes(payload.proof.domain.value error"
        );
        return false;
      }

      console.log("State init:", payload);
      const bocBytes = Buffer.from(payload.walletStateInit, "base64");

      const cell = Cell.fromBoc(bocBytes)[0];

      const hash = cell.hash().toString("hex");

      console.log("Hash:", hash);

      const addressHash = payload.address.slice(2);
      if (hash === addressHash) {
        return true;
      } else {
        console.log("Hashes do not match.");
      }
      
```

frontend:
```
APIService.post(`${ApiPaths.checkTonProof}`, {
      address: account.address,
      network: account.chain,
      public_key: account.publicKey,
      proof: {
        ...proof,
        state_init: account.walletStateInit,
      },
      userWalletAddress,
      walletStateInit: account.walletStateInit,
    });
```

**Comment by mzspcgg** [comment]
@Edgar-P-yan I use this code to find publicKey in stateInit: https://github.com/liketurbo/demo-dapp-backend-js/blob/main/src/routes/tonProof.ts.

You just need to add new version to "codes" variable. You can find the newest bytecode by opening your new created wallet address in the Tonscan.
<img width="1219" alt="image" src="https://github.com/user-attachments/assets/5909276c-40ec-492b-8df2-d3e36b614f60">

**Comment by Edgar-P-yan** [comment]
@mohsinrazabmd I don't get how it solves the issue. At https://github.com/liketurbo/demo-dapp-backend-js/blob/main/src/routes/tonProof.ts it still should parse the publicKey from `data`, but it has no code to do so for v5 as you can see here https://github.com/liketurbo/demo-dapp-backend-js/blob/4be035a18294c4575578e1c88e848cd94cbf4f2d/src/routes/tonProof.ts#L180 . The last version it supports is v4r2, so for v5 it will throw `400 unsupported wallet version`. To parse it correctly you need a `loadWalletV5Data` function, like this demo has `loadWalletV4data` for V4 and etc for the previous versions as well (see https://github.com/ton-connect/demo-dapp-with-react-ui/blob/b669298fc1e9709044c8bbe606b5d9029c5659ad/src/server/wrappers/wallets-data.ts#L51). I also don't see where you verify the signatures and authenticity.

Anyway, after posting my comment above i did some more digging, and found that `loadWalletV5Data` should look like this:
```ts
function loadWalletV5Data(cs: Slice) {
  const isSignatureAuthAllowed = cs.loadBit(); // here is a strange 1-bit shift introduced in v5
  const seqno = cs.loadUint(32);
  const walletId = cs.loadUint(32);
  const publicKey = cs.loadBuffer(32);
  const plugins = cs.loadMaybeRef();
  return { isSignatureAuthAllowed, seqno, publicKey, walletId, plugins };
}
```

I read the v5 wallet sources, and found this line: https://github.com/ton-org/ton/blob/80ca498b025178021380173a38b5069b09bfdf2a/src/wallets/v5r1/WalletContractV5R1.ts#L110
It turns out that the v5 shifts the data array by one bit. Not byte, but a bit. It's kinda strange decision, although i understand that maybe it's to optimize the memory usage, but the one-bit-shift also shifted the subsequent bytes, and made the comparison, searching and debugging this whole thing virtually impossible until i found the source codes. This is the reason why it took me about two weeks to figure this out without having any documentation.

The complete solution looks like this:
```ts
const knownWallets = [
  { contract: WalletContractV1R1, loadData: loadWalletV1Data },
  { contract: WalletContractV1R2, loadData: loadWalletV1Data },
  { contract: WalletContractV1R3, loadData: loadWalletV1Data },
  { contract: WalletContractV2R1, loadData: loadWalletV2Data },
  { contract: WalletContractV2R2, loadData: loadWalletV2Data },
  { contract: WalletContractV3R1, loadData: loadWalletV3Data },
  { contract: WalletContractV3R2, loadData: loadWalletV3Data },
  { contract: WalletContractV4R1, loadData: loadWalletV4Data },
  { contract: WalletContractV4R2, loadData: loadWalletV4Data },
  // added 2 lines:
  { contract: WalletContractV5R1, loadData: loadWalletV5Data },
  { contract: WalletContractV5Beta, loadData: loadWalletV4Data }, // the V5Beta's loadData algorithm matches the V4R2's one, not V5R1
].map(({ contract, loadData }) => ({
  contract: contract,
  loadData: loadData,
  wallet: contract.create({ workchain: 0, publicKey: Buffer.alloc(32) }),
}));

function loadWalletV1Data(cs: Slice) {
  const seqno = cs.loadUint(32);
  const publicKey = cs.loadBuffer(32);
  return { seqno, publicKey };
}

function loadWalletV2Data(cs: Slice) {
  const seqno = cs.loadUint(32);
  const publicKey = cs.loadBuffer(32);
  return { seqno, publicKey };
}

function loadWalletV3Data(cs: Slice) {
  const seqno = cs.loadUint(32);
  const walletId = cs.loadUint(32);
  const publicKey = cs.loadBuffer(32);
  return { seqno, publicKey, walletId };
}

function loadWalletV4Data(cs: Slice) {
  const seqno = cs.loadUint(32);
  const walletId = cs.loadUint(32);
  const publicKey = cs.loadBuffer(32);
  const plugins = cs.loadMaybeRef();
  return { seqno, publicKey, walletId, plugins };
}

// the missing loadWalletV5Data
function loadWalletV5Data(cs: Slice) {
  const isSignatureAuthAllowed = cs.loadBit(); // turns out the slice for v5 is shifted by one bit (not byte) to include this flag
  const seqno = cs.loadUint(32);
  const walletId = cs.loadUint(32);
  const publicKey = cs.loadBuffer(32);
  const plugins = cs.loadMaybeRef();
  return { isSignatureAuthAllowed, seqno, publicKey, walletId, plugins };
}

```

**Comment by Edgar-P-yan** [comment]
UPDATE: i just found out that there is a PR solving this that was opened just 2 days ago https://github.com/ton-connect/demo-dapp-with-react-ui/pull/18. Hope it'll merge soon
