### ISSUE TITLE
bug: mobile chrome return strategy fails

### ISSUE THREAD

**Issue by 7flash** [ton-connect/demo-dapp-with-react-ui#5]
In normal behaviour as it happens in mobile safari, universal link triggers tonkeeper directly; but in chrome it's going through middle tonkeeper webpage. Normally "back" return strategy would return user back to my app after confirmation in tonkeeper and that would trigger callback registered for authorization event, but in chrome it returns to tonkeeper page and manual swipe back to my app does not trigger callback.

The question is - how can my app get notified of user login skipping return strategy OR how can we avoid this page?

 
![image](https://user-images.githubusercontent.com/4569866/215256184-89f4ffce-65b5-4d5f-ad8b-0ff9c90586a7.png)

**Comment by 7flash** [comment]
Found temporary solution which is forcing to persist non-completed session:

```
        const session = connector.provider.session
        connector.provider.connectionStorage.storeConnection({
            type: 'http',
            session: session,
            connectEvent: null,
        })

```

**Comment by siandreev** [comment]
In the current version of the `tonconnect/ui` you cannot connect to the wallet inside of "incognito" window. Try use a normal tab instead of "incognito".
