### ISSUE TITLE
hi,https://ton-connect.github.io/demo-dapp/,    There is no openMask entry for this demo?

### ISSUE THREAD

**Issue by bryanForSafe** [ton-connect/demo-dapp-with-react-ui#6]
hi,https://ton-connect.github.io/demo-dapp/,    There is no openMask entry for this demo?

**Comment by siandreev** [comment]
[ton-connect.github.io/demo-dapp](https://ton-connect.github.io/demo-dapp/) works only with the TonKeeper. You can try OpenMask in the [demo-dapp-with-react-ui](https://ton-connect.github.io/demo-dapp-with-react-ui/)

(But you still can implement connection to the OpenMask with TonConnect in your app using any JS framework)
