### ISSUE TITLE
Proof checking does not work for other domains

### ISSUE THREAD

**Issue by troman29** [ton-connect/demo-dapp-with-react-ui#9]
I have deployed your demo page on my [website](https://static.obbana.ru/demo-dapp-with-react-ui/index.html) (with some changes). 

The proof check does not work now, although the wallet generates it correctly.

![image](https://github.com/ton-connect/demo-dapp-with-react-ui/assets/104140659/7d77a438-4244-4ea0-aa95-9144b75fa3a9)

**Comment by TomorrowLsn** [comment]
Hello, have you solved this problem?
